### ISSUE TITLE
https://rawgit.com/opengeospatial/CAT4.0/master/docs/18-065.html no longer available

### ISSUE THREAD

**Issue by KoalaGeo** [opengeospatial/ogcapi-records#18]
https://rawgit.com/opengeospatial/CAT4.0/master/docs/18-065.html no longer available

**Comment by jyutzler** [comment]
We are pretty sure 18-065 is obsolete, but we are going to turn https://github.com/opengeospatial/ogcapi-records/blob/master/core/standard/20-004.adoc into something with a permalink so that it would be accessible through a similar URL.

**Comment by jyutzler** [comment]
As an aside, if GitHub were able to resolve https://github.com/github/markup/issues/1095, this would be less of an issue for us.

**Comment by KoalaGeo** [comment]
As an aside, if you moved to rst instead of adoc that would work with current infrastructure. 

example documentation : https://github.com/BritishGeologicalSurvey/Groundhog 

This documentation is written in ReStructured Text hosted on GitHub pages, built using Sphinx via Gitub Actions each time theres a commit to the master. https://britishgeologicalsurvey.github.io/Groundhog/#documenting-the-documentation

**Comment by jyutzler** [comment]
AsciiDoc can also be rendered through GitHub.io, but that requires someone to set up the pipeline. Direct rendering of AsciiDoc (including "includes", as requested in that other ticket) would obviate that need.

**Comment by tomkralidis** [comment]
I think AsciiDoc is the OGC standard for writing up the standards.  To echo @jyutzler, we'll follow the OGC workflow for publishing the AsciiDoc accordingly.

**Comment by tomkralidis** [comment]
@pvretano I think you mentioned discussing this with OGC?

We could also setup a GitHub workflow (saving the below to `.github/workflows/main.yml`) like (untested):

```yaml
name: CI

on: [ push , pull_request ]

jobs:
  make_xml:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.ref }}
    - name: install asciidoctor dependencies
      run: |
        gem install asciidoctor --pre
        gem install asciidoctor-pdf --pre
    - name: create standard document in HTML and PDF
      run: | 
        cd core/standard
        asciidoctor --trace -o 20-004.html 20-004.adoc
        asciidoctor -r asciidoctor-pdf --trace -b pdf -o 20-004.pdf 20-004.adoc
        git commit -m "re-publish draft" *.pdf *.html
        git push
```

**Comment by pvretano** [comment]
@tomkralidis Sent an email to OGC last week about this.  Lets let them set it up since they have a standard workflow for this.  I'll follow up again.

**Comment by tomkralidis** [comment]
Looks like this is working now: http://docs.opengeospatial.org/DRAFTS/20-004.html

Can someone edit the heading text of this repo from:

Text: Public repo for CAT4.0 work http://www.github.com/opengeospatial/…
URL: http://www.github.com/opengeospatial/CAT4.0

To: 

Text: An open standard for searching and discovering geospatial resources on the web.
URL: https://docs.opengeospatial.org/DRAFTS/20-004.html

**Comment by pvretano** [comment]
@tomkralidis I think I can make the change but before I do, isn't "searching" and "discovery" the same thing?

**Comment by tomkralidis** [comment]
@pvretano I paraphrased from https://docs.opengeospatial.org/DRAFTS/20-004.html#_scope (we could change that too if we want).  I'm fine with just using "discovery".

**Comment by pvretano** [comment]
@tomkralidis I updates the header.  The scope does indeed use the phrase "discovery and search" and then goes on to explain the distinction.  Regardless I think the scope needs work but that will happen in the course of editing the document.  If you don't object, I will close this issue now since the primary problem has been resolved.

**Comment by tomkralidis** [comment]
@pvretano I'm still seeing http://www.github.com/opengeospatial/CAT4.0 as the website (should now be https://docs.opengeospatial.org/DRAFTS/20-004.html)

**Comment by pvretano** [comment]
@tomkralidis caching issue maybe?  I see the revised text there and in the list of OGC repos.

**Comment by tomkralidis** [comment]
@pvretano see the link beside the updated text in the below screenshot:

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/910430/83469446-b5567280-a44d-11ea-899a-1168eaaa44c9.png">

**Comment by pvretano** [comment]
@tomkralidis better?

**Comment by tomkralidis** [comment]
Excellent!
